server.servlet.context-path=/workintech
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Workintech-Sprint19-C2
spring.datasource.username=postgres
spring.datasource.password=852456
spring.jpa.hibernate.ddl-auto=update